### ISSUE TITLE
[BUG]: 正式发布项目后，通过https://tanglei.top无法正常显示，但是用localhost访问就可以

### ISSUE THREAD

**Issue by skytangleisky** [Orillusion/orillusion#112]
![截屏2023-05-07 20 40 07](https://user-images.githubusercontent.com/26360493/236678202-035619d2-bb34-48e6-846d-d4445577d6e1.png)

**Comment by lslzl3000** [comment]
请使用最新0.6+测试，新版api变化较大，已移除dat.gui的依赖
