### ISSUE TITLE
[FR]: Engine3D destroy and release

### ISSUE THREAD

**Issue by skytangleisky** [Orillusion/orillusion#125]
The `Engine3D` could be destroyed and re-create in one window context

```js
  async function demo(){
    //init first Engine3D instance
    await Engine3D.init()
    // ...
    // Destroy it later
    await Engine3D.destroy()
    
    //init a second Engine3D instance
    await Engine3D.init()
    // could destroy it sometime
    await Engine3D.Destroy()
    // ...
  }
  demo()
```

The Engine3D memory and resources should be released/cleaned after destroy

**Comment by lslzl3000** [comment]
Did you mean create multi engine instance?

**Comment by skytangleisky** [comment]
It's right that the Engine3D could be destroyed and re-create a new one in one window context.
