### ISSUE TITLE
[FR]: 文档是否有提供playground的想法

### ISSUE THREAD

**Issue by mankeheaven** [Orillusion/orillusion#134]
文档和示例对应的，看你们是否愿意提供一些playground，如http://examples.maptalks.com/  或者这种 
 https://playground.babylonjs.com/

**Comment by lslzl3000** [comment]
社区里其实有很多这种第三方的playground，目前阶段我们可能会基于 codepen 来做一些playground的例子，比如 https://codepen.io/orillusion/pen/QWQrRmr
后续可以将这些链接关键到文档里方便用户查看

**Comment by mankeheaven** [comment]
谢谢, 期待这个工作能带来很好的体验。你们的文档写的很nice。

**Comment by lslzl3000** [comment]
已在文档中加入 codepen 的链接，所有 demo 都可以跳转 codepen 进行交互编辑
