### ISSUE TITLE
[FR]:性能分析是否有提供spector的想法？ 

### ISSUE THREAD

**Issue by mankeheaven** [Orillusion/orillusion#135]
目前仅提供stats感觉比较弱，不知道你们日常是如何解决性能问题的？

babylonjs提供了类似于以下这种方式  https://github.com/BabylonJS/Spector.js

![image](https://github.com/Orillusion/orillusion/assets/17426397/91604d85-5e12-4f70-8de3-2b8236019a95)

![image](https://github.com/Orillusion/orillusion/assets/17426397/99f28ad5-186e-4fad-80e2-46adb679fb48)

**Comment by lslzl3000** [comment]
目前webgpu确实没有特别好的debug方式，wgsl也没有特别好的debug工具，Chrome本身也没有对webgpu的性能分析做很好的支持，这个跟webgl确实不太一样

我们后续会对 stats 加入更多的参数报告，也希望大家提供建议，最好能共同丰富webgpu的生态

**Comment by mankeheaven** [comment]
thank you, 我也会持续关注和研究这块，期望有一天能给orillusion提供一些贡献。
对你们的工作表示赞同。
