### ISSUE TITLE
[BUG]: 在使用自定义canvas时，canvas会自己自动变得很大，无法修改

### ISSUE THREAD

**Issue by FliPPeDround** [Orillusion/orillusion#159]
## Bug描述
在使用自定义canvas时，canvas会自己自动变得很大，无法修改
```js
const canvas = document.getElementById('canvas')
await Engine3D.init({
   canvasConfig: { canvas }
})

```

## Bug复现流程
 <canvas id="canvas"></canvas>

const canvas = document.getElementById('canvas')

## 期待的结果
简介明要的阐述你期待发生什么结果

## 报错截图
如果可以，提供发生错误的截图

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, e.g. 0.6.1

## 本机系统 (请填写完整):
 - OS: [win]
 - Browser [edge]
 - Version [113.0.1774.42 (正式版本) (64 位)]

## 代码示例
https://codepen.io/FliPPeDround/pen/mdzzBBJ

## 其他信息
添加关于bug的其他描述信息

**Comment by lslzl3000** [comment]
![Screenshot 2023-05-18 at 13 01 18](https://github.com/Orillusion/orillusion/assets/3398981/0dfbfb18-7080-4d95-ad91-fa60058dd33c)

我这里测试正常，不加css的话 canvas 是默认大小，也可以通过 css 改变大小

![Screenshot 2023-05-18 at 13 02 59](https://github.com/Orillusion/orillusion/assets/3398981/05737086-35e4-4a4b-9c14-25ad5f7fd47e)

**Comment by FliPPeDround** [comment]
![动画](https://github.com/Orillusion/orillusion/assets/70848683/bed2be2a-42dd-4bbb-b6fe-ed7ff14dcafc)


我确实遇到了这个问题，在其他电脑上也复现了，我还需要提供什么信息可以帮助排除这个问题

**Comment by lslzl3000** [comment]
@FliPPeDround 已排查到问题所在，主要是没有手动规范canvas的css大小，在dpr不等于1的屏幕上会导致canvas会根据内容大小resize，从而循环触发resize越来越大。

目前来讲，请手动设置一个 css 来规范canvas style 的 width 和 height，不要使用默认值（即无style width height）
我们后面会优化resize的方案，避免这种情况

**Comment by lslzl3000** [comment]
已在 #163 中修复canvas无默认大小的情况，会跟随下个版本发布
