### ISSUE TITLE
[BUG]: MeshColliderShape does not work

### ISSUE THREAD

**Issue by Grabli66** [Orillusion/orillusion#222]
## Describe the bug
physics.es.js:7513 Uncaught TypeError: Cannot read properties of undefined (reading 'calculateLocalInertia')
    at zF.addAmmoRigidbody (physics.es.js:7513:7)
    at zF.initRigidbody (physics.es.js:7522:10)
    at zF.start (physics.es.js:7465:10)
    at zF.__start (orillusion.es.js:3283:47370)
    at orillusion.es.js:3283:79181
    at Array.forEach (<anonymous>)
    at orillusion.es.js:3283:79167
    at Map.forEach (<anonymous>)
    at Ld.waitUpdate (orillusion.es.js:3283:79149)
    at rn.renderFrame (orillusion.es.js:3968:17223)

## To Reproduce
```typescript
import * as ori from '@orillusion/core'
import * as phy from "@orillusion/physics"

export class Game {
    async start() {
        await ori.Engine3D.init({
            renderLoop: () => {
                if (phy.Physics.isInited) {
                    phy.Physics.update();
                }
            }
        });

        await phy.Physics.init();

        let scene = new ori.Scene3D();
        let sky = scene.addComponent(ori.AtmosphericComponent);        
        sky.displaySun = false;
        
        let cameraObj = new ori.Object3D();
        let camera = cameraObj.addComponent(ori.Camera3D);
        camera.perspective(60, ori.Engine3D.aspect, 1, 5000.0);
        let controller = cameraObj.addComponent(ori.HoverCameraController);
        controller.setCamera(0, -20, 15);
        scene.addChild(cameraObj);        

        let box = new ori.Object3D();
        let boxMesh = box.addComponent(ori.MeshRenderer);
        boxMesh.geometry = new ori.BoxGeometry(2, 2, 2);
        boxMesh.material = new ori.LitMaterial();
        box.transform.y = 5;
        let boxBody = box.addComponent(phy.Rigidbody);        
        boxBody.mass = 1;        
        let boxCollider = box.addComponent(ori.ColliderComponent);
        boxCollider.shape = new ori.MeshColliderShape();        
        scene.addChild(box);

        let view = new ori.View3D();
        view.scene = scene;
        view.camera = camera;
        ori.Engine3D.startRenderView(view)
    }
}

let game = new Game();
game.start();
```

## Orillusion engine version
0.6.5

## Platform (please complete the following information)
Windows
Chrome 114

## Additional context
I think it's because of this
https://github.com/Orillusion/orillusion/blob/841047eb884d2194164d3181f5185d813091a591/packages/physics/Rigidbody.ts#LL177C37-L177C37

**Comment by X-OldGentleMan** [comment]
Here we need to pay attention to the physical life cycle. First initialize the Physics engine, then initialize the 3d engine
