### ISSUE TITLE
[BUG]: 静止物体修改velocity属性无效

### ISSUE THREAD

**Issue by alan-best** [Orillusion/orillusion#230]
## Bug描述
静止物体修改velocity属性无效

## Bug复现流程
1. 创建多个几何体
2. 设置pick事件监听器，在点击物体时修改物体刚体组件的velocity属性
3. 正在运动的物体修改velocity正常，但静止一段时间后的物体修改velocity无效

## 期待的结果
静止一段时间后的物体修改velocity属性后可以继续运动

## 测试引擎版本:
0.6.5

## 本机系统 (请填写完整):
 - OS: [Windows]
 - Browser: [Edge]
 - Version: [116.0.1923.0]

## 代码示例
https://codepen.io/alan-best/pen/qBQqgMG

## 其他信息
通过直接调用btRigdibody的addForce方法也存在同样问题，但是在修改velocity之前调用
```javascript
rigidbody.btRigidbody.activate(true);
```
可以解决bug

**Comment by X-OldGentleMan** [comment]
我们引擎目前是直接使用Ammo的物理引擎，这个问题可以参考 https://github.com/kripken/ammo.js ， 或者参考Bullet 的官方文档 http://bulletphysics.org/
