### ISSUE TITLE
[BUG]:  无法同时初始化两个  Engine3D.init

### ISSUE THREAD

**Issue by partiality** [Orillusion/orillusion#244]
## Bug描述
无法同时创建两个canvas 用于展示两个3d 场景

## 期待的结果
简介明要的阐述你期待发生什么结果

## 报错截图
如果可以，提供发生错误的截图

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, e.g. 0.6.5

## 本机系统 (请填写完整):
 - OS: [e.g. win]
 - Browser: [e.g. chrome]
 - Version: [e.g. 114]

## 代码示例
https://codepen.io/partiality/pen/dyQvxEZ

## Bug定位
我不知时候还有其他方式用于配置多个canvas 的方式   
至少按我代码示例所写     问题应该在  
orillusion/src/gfx/graphics/webGpu/Context3D.ts
![image](https://github.com/Orillusion/orillusion/assets/27626874/1a3a82b0-f828-445c-b84b-dc63308edddf)

Context3D 这个类在这就实例化了  并且作为导出对象进行使用   这对于整个来说就是全局对象  这不就代表了整个网页上下文就只能存在一个canvas

## 其他信息
添加关于bug的其他描述信息

**Comment by JingwenBai** [comment]
感谢反馈！这个问题之前也有小伙伴提过，由于最近开发任务比较紧张，我们会尽快解决~
