### ISSUE TITLE
[BUG]: 无法通过  material  下的baseColor 进行修改颜色

### ISSUE THREAD

**Issue by partiality** [Orillusion/orillusion#246]
## Bug描述
无法通过  material  下的baseColor 进行修改颜色

## 期待的结果
通过material.baseColor.hexToRGB 要能改变材质颜色

## 报错截图
如果可以，提供发生错误的截图

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, e.g. 0.6.1

## 本机系统 (请填写完整):
 - OS: [e.g. win, mac, android]
 - Browser: [e.g. chrome]
 - Version: [e.g. 113]

## 本机配置
- CPU: e.g. Intel I7 13700, Apple M2
- Graphics Card: e.g, Intel UHD 670, Apple M2, GTX 3070

## 错误定位
这里每次都会重新创建一个Color对象  导致原本的Color对象引用丢失
![image](https://github.com/Orillusion/orillusion/assets/27626874/28647b63-b3ef-434d-8956-b2078daca679)

## 代码示例
https://codepen.io/partiality/pen/KKrmgab

## 其他信息
添加关于bug的其他描述信息

**Comment by JingwenBai** [comment]
感谢反馈！最近开发任务比较紧张，我们会尽快回复的！

**Comment by hellmor** [comment]
建议按照这种方式使用：
let color = new Color();
color.hexToRGB(0xf44336);
material.baseColor = color;
