### ISSUE TITLE
[FR]:  希望在npm上发布的版本中, 增加不压缩的版本

### ISSUE THREAD

**Issue by chuanxinwong** [Orillusion/orillusion#253]
我在npm的安装目录下, 只看到 
node_modules\@orillusion\core\dist\orillusion.es.js ,
node_modules\@orillusion\core\dist\orillusion.umd.js ,
他们都是压缩过的版本;    
我npm安装该模块后, 一般喜欢在控制台打印对象出来,  来查看对象上的一些属性或者可以调用的函数, 或该类的继承关系;     
让开发者可以手动自己使用不压缩的版本进行调试!    
非常感谢!

**Comment by lslzl3000** [comment]
感谢反馈，下一个版本中会加入不压缩的 max 版本
