### ISSUE TITLE
两个场景模型页面相互路由切换之后视图不渲染。

### ISSUE THREAD

**Issue by Temurayl** [Orillusion/orillusion#278]
两个场景模型页面相互路由切换之后出现报错，且页面空白 视图不渲染，按F5刷新页面后模型正常渲染且不报错，是缺少什么设置吗？望回复！！！
![image](https://github.com/Orillusion/orillusion/assets/64075669/80dfa88b-9ce5-4917-8189-b52ac9da16fd)
![image](https://github.com/Orillusion/orillusion/assets/64075669/b1d49937-d687-4138-9a7d-e065df96f64e)

**Comment by lslzl3000** [comment]
目前无法在同一页面中创建多个Engine实例，同 #125 #244 
我们稍后会尝试解决这个问题，目前可以像官网一样，通过 iframe 把多个 Engine 进行隔离，来切换显示或者布局

**Comment by Temurayl** [comment]
> 目前无法在同一页面中创建多个Engine实例，同 #125 #244 我们稍后会尝试解决这个问题，目前可以像官网一样，通过 iframe 把多个 Engine 进行隔离，来切换显示或者布局

那可以创建多个实例这个问题大概什么时候能够解决呢？

**Comment by JingwenBai** [comment]
可以具体描述下我们的需求么？通过iframe隔离的方式具体遇到哪些问题呢？

**Comment by Temurayl** [comment]
1、目前解决了，若什么时候不用iframe隔离就更好了
2 、还有希望能使用IndexedDB存储模型数据，能存储，能读取使用
3、玛雅场景化建模时整个模型比较小，视图渲染时将模型放大1000倍，标签的坐标点直接从玛雅采集且渲染时放大10倍左右，此时标签位置距离坐标点会有一段距离r ，旋转视图时标签以坐标点为圆心r为半径旋转。 离坐标系原点越远这个半径r的偏差越大



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月13日 09:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Orillusion/orillusion] 两个场景模型页面相互路由切换之后视图不渲染。 (Issue #278) |

可以具体描述下我们的需求么？通过iframe隔离的方式具体遇到哪些问题呢？
