### ISSUE TITLE
[BUG]: 相机矩阵问题

### ISSUE THREAD

**Issue by GGBond-GIS** [Orillusion/orillusion#282]
## Bug描述
threejs和ori同样的相机矩阵看到的东西不同

## 期待的结果
应该是正对着球体
![image](https://github.com/Orillusion/orillusion/assets/92559206/4f14da55-cdb9-4d89-8740-85becd515a67)

## 错误截图
代码示例中矩阵呈现的效果
![image](https://github.com/Orillusion/orillusion/assets/92559206/7df0d9da-3292-4c49-aec5-d51bee2b1bf2)

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, e.g. 0.6.8

## 代码示例
```
//这里写的是threejs的方法
			new SphereGeometry(6378137, 32, 16, 0);
			const camera = new PerspectiveCamera(
				31,
				window.innerWidth / window.innerHeight,
				0.1,
				10000000000
			);
			
			let matrix = new Matrix4();
			matrix.set(
				0.6060509940664182,
				-0.5577070828031724,
				0.5671551836863363,
				18982212.634013783,
				0.7954257932649069,
				0.4249283022912731,
				-0.43212700137893495,
				-14462931.594415683,
				-1.8041124150158798e-15,
				0.713020860636652,
				0.701142818758752,
				23424319.975570545,
				0,
				0,
				0,
				1
			);
            // {
			// 	0.6060509940664182,
			// 		0.7954257932649069,
			// 		-1.8041124150158798e-15,
			// 		0,
			// 		-0.5577070828031724,
			// 		0.4249283022912731,
			// 		0.713020860636652,
			// 		0,
			// 		0.5671551836863363,
			// 		-0.43212700137893495,
			// 		0.701142818758752,
			// 		0,
			// 		18982212.634013783,
			// 		-14462931.594415683,
			// 		23424319.975570545,
			// 		1;
			// }
			matrix.decompose(camera.position, camera.quaternion, camera.scale);
//这里写的代码在threejs里是能正常显示的
//我通过计算出来的position，quaternion，scale赋给ori的相机
```

## 其他信息
这里ori的相机我加了个父节点
Object3D-->Object3D-->addComponent(Camera3D)

**Comment by JingwenBai** [comment]
Please put this code into here: "https://codepen.io/", so that we could run this code and confirm the problem quickly. Thanks!

**Comment by GGBond-GIS** [comment]
`
{
    "0": -0.6174283623695374,
    "1": -0.7866271138191223,
    "2": 0.0001761471212375909,
    "3": 0,
    "4": -0.52712082862854,
    "5": 0.4139065146446228,
    "6": 0.7421758770942688,
    "7": 0,
    "8": -0.5838885307312012,
    "9": 0.4581475555896759,
    "10": -0.6702051758766174,
    "11": 0,
    "12": -18773886,
    "13": 14734240,
    "14": -21564268,
    "15": 1
}
`
部分矩阵会有问题例如这个
![image](https://github.com/Orillusion/orillusion/assets/92559206/91fad1d0-fdc0-4612-9d83-d4cd9c8c2cc7)
