### ISSUE TITLE
Some feature suggestions for version 0.5

### ISSUE THREAD

**Issue by sbfkcel** [Orillusion/orillusion#3]
- Collider
     - Add cylinder preset
- UI adds some after effects
     - eg: frosted glass, color overlay mode, etc.
     - Text allows gradient colors, shadows, Vertical text, right to right
     - Basic rectangular shape, rounded corners allowed, gradient fill, shadow, stroke, stroke gradient
- Particle animation
     - more emulators

If the size of the renderer is considered, it can be added in an extended form.

**Comment by orillusion-admin** [comment]
Great first issue! We are discussing these features, will let you know if get any progress.
