### ISSUE TITLE
[BUG]: 通过点击事件修改相机位置及观察目标位置，相机位置更改了，但是观察目标始终没有改变

### ISSUE THREAD

**Issue by Temurayl** [Orillusion/orillusion#300]
## Bug描述
初始化时，对相机进行 位置及观察目标位置 进行设置如下图
this.camera.lookAt(new Vector3(750, 360, 800), new Vector3(0, 0, 0), new Vector3(0, 0, 0));

![image](https://github.com/Orillusion/orillusion/assets/64075669/9452530d-955a-444e-a5d5-fa3bc9412267)

通过点击事件更改相机的位置及观察目标位置时，相机的位置更改了，但是观察目标位置始终是初始化的位置
this.camera.lookAt(new Vector3(356.859, 95.694, 92.603), new Vector3(355.926, 5, 24.728), new Vector3(0, 0, 0));

![image](https://github.com/Orillusion/orillusion/assets/64075669/8158b7cb-f3ed-431e-bac2-b8dab2cdadc2)

**Comment by lslzl3000** [comment]
能否提供一个简单的 codepen 的示例，简化一下代码，把核心的控制表现一下就行

**Comment by Temurayl** [comment]
> 能否提供一个简单的 codepen 的示例，把核心的代码体现一下就行 或者把核心部分代码贴出来
由于codepen网站打开项目总是白屏，所以只能提供示例的JS代码部分了，改变相机的位置及视角在 18行及44行 里面有标注.视角1和视角2，视角1为初始化位置，视角2为改变后 相机观察目标位置，此处我给的随机值，点击模型进行相机位置改变，但相机观察目标位置无法改变
https://codepen.io/Temurayl/pen/jOXLmXm

**Comment by lslzl3000** [comment]
ok，大概明白什么问题了，主要是 controller 和 camera.lookAt 有冲突的问题
各个controller 里都有自己的管理 camera 的方法，添加 controller 前可以使用 camera.lookat 进行控制，添加后由于不同的控制逻辑，可能会和 cmaera.lookat 的修改有冲突，一般是以controller 的逻辑为主

比如使用 OrbitController，它支持直接修改 cameraObject 的position，但其自身拥有自己的 target 维护逻辑，会实时覆盖cmaera.lookAt ，必须用对应的属性来控制 target：
```js
let orbit  = cameraObj.addComponent(OrbitController)
// 修改 camera 位置
cameraObj.position = new Vector3(x,x,x)
// 修改 target
orbit.target = new Vector3(x,x,x)
``` 

如果使用 HoverController, 则必须使用 `setCamera(roll, pitch, distance, target?)` 来控制 `(roll, pitch, distance)` 和 `target`

**Comment by Temurayl** [comment]
想问一下这引擎在什么环境下才能稳定运行呢，昨天就可以正常运行，今天就无法正常运行，开始报错 浏览器不支持GPU

![image](https://github.com/Orillusion/orillusion/assets/64075669/862b8b6a-a0e7-4aa0-96db-18cc7bccb8f7)
