### ISSUE TITLE
[BUG]: 官方文档：粒子-基本模块-纹理图集模块不显示，控制台报错

### ISSUE THREAD

**Issue by s442901055** [Orillusion/orillusion#301]
2023年9月15日发现
前段时间我记得没升级0.6.9的时候还可以看
上面几个模块都可以正常显示
最后一个纹理图集模块加载不出来

![image](https://github.com/Orillusion/orillusion/assets/39576034/26a3f1cc-e518-46d6-b223-db485ee67a8c)
![image](https://github.com/Orillusion/orillusion/assets/39576034/04a763eb-2c15-494a-91fb-9768a02583fa)

**Comment by lslzl3000** [comment]
感谢反馈，已修复问题，稍后会更新 particle 版本
