### ISSUE TITLE
[FR]: What about sounds ?

### ISSUE THREAD

**Issue by tvortsa** [Orillusion/orillusion#302]
If the engine have some sound sub-system or i must use something from outside?
Thank you!

**Comment by lslzl3000** [comment]
We have some basic audio components for test, you can review samples: https://github.com/Orillusion/orillusion/tree/dev/samples/audio

The Web/HTML audio is strong enough for most cases, so we only add few things on audio system, mainly to cover dynamic position audio. You can send PRs or issues to tell us more features
