### ISSUE TITLE
[BUG]: texture Count Exceeded the maximum limit of 7

### ISSUE THREAD

**Issue by Temurayl** [Orillusion/orillusion#304]
## Bug描述
简单明晰的描述问题所在
这个是对文本有限制吗 
![image](https://github.com/Orillusion/orillusion/assets/64075669/b96e586d-ea0d-47aa-9275-b12e67e15e28)

## Bug复现流程
通过以下步骤产生bug:
1. 创建 '...'
2. 点击 '...'
3. 删除 '...'
4. 出现错误 '...'

## 测试引擎版本:
0.6.9

**Comment by lslzl3000** [comment]
这个请补充一下代码吧，最好有复现步骤

**Comment by Temurayl** [comment]
> 这个请补充一下代码吧，最好有复现步骤

https://codepen.io/Temurayl/pen/ZEVaWbb?editors=0011
核心代码在里面的for循环中
不知道有没有更好的解决办法，在文档中暂未看到相关需求的一个相关介绍

![image](https://github.com/Orillusion/orillusion/assets/64075669/5daf9969-5d2d-4f3b-af7a-b3fb1cdb0e5c)
![image](https://github.com/Orillusion/orillusion/assets/64075669/9c657032-a791-49a6-8648-2114dad1a9e1)

**Comment by OriIIusion** [comment]
我把这几段代码拿出了for循环就能渲染出8个了

```
let bitmapTexture2D = new BitmapTexture2D()
bitmapTexture2D.flipY = true
await bitmapTexture2D.load('https://cdn.orillusion.com/images/webgpu.png')
let s = makeAloneSprite('webgpu', bitmapTexture2D)
```
![image](https://github.com/Orillusion/orillusion/assets/39576034/670221c3-ff62-462b-9b36-1bc5c1720079)

**Comment by Temurayl** [comment]
那如果是多个图片是不是这样写就可以了
![image](https://github.com/Orillusion/orillusion/assets/64075669/b0fe11ca-3af0-4b52-9ed4-71051a07f4ec)

**Comment by hellmor** [comment]
单个UIPanel实例时会自动创建一个UI相关的材质球，这单个材质球对于用到的贴图有数量限制。
在当前Issue里面，贴图数量超过限制，那么你可以将这些单元分组到不同的UIPanel里面去。

**Comment by hellmor** [comment]
> 单个UIPanel实例时会自动创建一个UI相关的材质球，这单个材质球对于用到的贴图有数量限制。 在当前Issue里面，贴图数量超过限制，那么你可以将这些单元分组到不同的UIPanel里面去。

当前版本可以先调整业务代码去规避这个限制。在未来，说不定这个问题就优化掉了。
