### ISSUE TITLE
[FR]: 关于标签面板数据更新问题。

### ISSUE THREAD

**Issue by Temurayl** [Orillusion/orillusion#307]
## Describe

左边是事件触发控制器，右边是模型与标签面板。当我点击左边的开启按钮时，期望右边对应的房间上方的标签的背景图、icon、文字进行更新，这种情况该怎么做呢？文档中暂未找到更新标签数据的相关说明。

![image](https://github.com/Orillusion/orillusion/assets/64075669/894c1ad0-b7c8-4edc-894c-dd0eaf064fad)

**Comment by OriIIusion** [comment]
当点击按钮时，获取对应面板的UIImage和UIText，然后修改UIImage.sprite和UIText.text就可以了吧？

**Comment by Temurayl** [comment]
> 当点击按钮时，获取对应面板的UIImage和UIText，然后修改UIImage.sprite和UIText.text就可以了吧？

可以给个实例吗？不是太理解 具体的获取与更新数据

**Comment by OriIIusion** [comment]
https://codepen.io/OriIIusion/pen/xxmpowX

看你的事件触发在哪做的了 我这里用的Orillusion中的按钮 直接修改对应的颜色 icon 或者文字就行
