### ISSUE TITLE
[BUG]: 模型人物骨骼动画

### ISSUE THREAD

**Issue by Temurayl** [Orillusion/orillusion#312]
## Bug描述
简单明晰：

这几个动画在3D建模里面是怎么制作的，能大概说明一下制作过程吗？ 

![bdc351c0fe51ab0a95b7500ec93154f](https://github.com/Orillusion/orillusion/assets/64075669/e362e057-83c3-4c16-a43f-058eb48ca216)

## Bug复现流程
通过以下步骤产生bug:
1. 创建 '...'
2. 点击 '...'
3. 删除 '...'
4. 出现错误 '...'

## 期待的结果
简介明要的阐述你期待发生什么结果

## 报错截图
如果可以，提供发生错误的截图

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, e.g. 0.6.1

## 本机系统 (请填写完整):
 - OS: [e.g. win, mac, android]
 - Browser: [e.g. chrome]
 - Version: [e.g. 113]

## 本机配置
- CPU: e.g. Intel I7 13700, Apple M2
- Graphics Card: e.g, Intel UHD 670, Apple M2, GTX 3070

## 代码示例
如果有sandbox/codepen的代码示例链接，请提供  
您可以修改 https://codepen.io/pen?template=QWQrRmr 来创建一个简单的演示

## 其他信息
添加关于bug的其他描述信息

**Comment by OriIIusion** [comment]
通常动画的制作过程是
建模-搭建骨骼-蒙皮绑定-制作骨骼动画

搭建骨骼：创建骨骼，调整骨骼与模型大小匹配，尤其是关节位置要与模型关节位置对齐
蒙皮绑定：可以理解为将模型绑定在骨骼上，模型上的每个点都会被一个骨骼或者多个骨骼影响，这个影响大小值叫做权重，整个蒙皮绑定的过程也是调整权重的过程
骨骼动画：对骨骼进行动画关键帧的制作，骨骼运动从而使模型跟着运动。

**Comment by Temurayl** [comment]
在3D建模中怎么区分不同时间段的动画的，动画剪辑数据对象是怎么加到模型上面的
![image](https://github.com/Orillusion/orillusion/assets/64075669/9236f1d6-5cf5-4ab4-8e6c-f8a3def1af6c)
