### ISSUE TITLE
[FR]: 想提交一些sample

### ISSUE THREAD

**Issue by OriIIusion** [Orillusion/orillusion#349]
1.是提交到orillusion这里还是orillusion-web这里？
2.公众号上次文章里有说出新内容教大家如何提交，什么时候发？
![image](https://github.com/Orillusion/orillusion/assets/39576034/cdb20544-8928-4c71-b17c-869186d9adba)

**Comment by JingwenBai** [comment]
下周就会发布啦~感谢支持哈！
