### ISSUE TITLE
[BUG]: Ray射线 r1.at is not a function

### ISSUE THREAD

**Issue by YBbread** [Orillusion/orillusion#351]
## Bug描述
官网工具库示例中
let r1 = new Ray();
// 计算射线上的某一点
let result1 = r1.at(1);

![image](https://github.com/Orillusion/orillusion/assets/29371745/3a87c49f-abbf-44c3-9398-67b9c3eb3770)

**Comment by OriIIusion** [comment]
let ray = new Ray();
ray.pointAt(1);

Ray没有at方法啊 倒是有个pointAt
你试试

**Comment by YBbread** [comment]
> let ray = new Ray(); ray.pointAt(1);
> 
> Ray没有at方法啊 倒是有个pointAt 你试试

谢谢   可以用到。pointAt 有效
