### ISSUE TITLE
[BUG]: dev分支，物理模块不能用了

### ISSUE THREAD

**Issue by OriIIusion** [Orillusion/orillusion#356]
## Bug描述
dev分支中，三个物理sample都打不开了，新建一个sample，仅仅await Physics.init();都不行，报一样的错
![image](https://github.com/Orillusion/orillusion/assets/39576034/e2d4c523-7537-4148-9fde-8eacf69b8098)

main分支可以打开

**Comment by lslzl3000** [comment]
已更新修复新版Ammo用法
