### ISSUE TITLE
[BUG]: 设置拾取模式为pixel后，添加bloompost报错

### ISSUE THREAD

**Issue by OriIIusion** [Orillusion/orillusion#382]
## Bug描述
设置拾取模式为pixel后，添加bloompost报错，无法添加bloom
将拾取模式的代码注释以后，可以添加bloom

## Bug复现流程
https://codepen.io/OriIIusion/pen/gOyWaEq
看此案例
1.默认开启pick，然后添加bloom，发现报错了，bloom没添加上
2.将pickmode代码注释掉，bloom可以正常添加

## 报错截图
![image](https://github.com/Orillusion/orillusion/assets/39576034/59ed4fc3-25ec-4e0d-8c4e-f9761788ef63)

## 测试引擎版本:
0.7.2

**Comment by hellmor** [comment]
Bloom的effect添加方式不对。你的sample中添加成功后效果如下
![image](https://github.com/Orillusion/orillusion/assets/10559053/97a32c2f-0bbe-4f53-a00a-4ff06df2c0bc)

**Comment by OriIIusion** [comment]
感谢指点，已解决。

目前文档中只有通过以下一种方式添加
let postProcessing = this.scene.addComponent(PostProcessingComponent);
postProcessing.addPost(BloomPost);


建议增加说明还有另一种添加的方式，并且增加提示按原来的方式添加和设置拾取模式为pixel时会发生冲突

**Comment by OriIIusion** [comment]
发现了一种新的解决办法

`Engine3D.startRenderView()`源码中有这段
`if (this.setting.pick.mode == "pixel") {
        let postProcessing = view.scene.getOrAddComponent(PostProcessingComponent);
        postProcessing.addPost(FXAAPost);
}`

所以这样也可以添加
`let post = scene.getOrAddComponent(PostProcessingComponent);
post.addPost(BloomPost);`

**Comment by lslzl3000** [comment]
resolved in v0.8
