### ISSUE TITLE
[BUG]:  天空盒bitmapcube加载注释错误

### ISSUE THREAD

**Issue by Davidyanlong** [Orillusion/orillusion#388]
## Bug描述
这里的注释顺序是nx, px, ,py, ny, nz, pz
![f45506e6f0938e6f360a31781775dac](https://github.com/Orillusion/orillusion/assets/10626549/77f66637-336d-4c23-9cb0-e36098270d2a)
正确的顺序应该是px, nx, py, ny, pz, nz
## Bug复现流程
![ef5a0978f64ea4f1238460e038ac618](https://github.com/Orillusion/orillusion/assets/10626549/f78d2594-aab4-4c2a-a9d7-4b47ac37b755)

## 期待的结果
正确的呈现天空盒

## 报错截图
如果可以，提供发生错误的截图

## 测试引擎版本:
v0.7.2

## 本机系统 (请填写完整):
 - OS: win
 - Browser: chrome
 - Version: 123

## 本机配置
- CPU: e.g. Intel I7 13700, Apple M2
- Graphics Card: e.g, Intel UHD 670, Apple M2, GTX 3070

**Comment by orillusion-admin** [comment]
能给我们一套比较完善的素材么？我们用来测试下，看看这个顺序是具体哪里的问题~
