### ISSUE TITLE
[FR]: 计划什么时候推出1.0版本，五个月没有出新版本了，停滞了？

### ISSUE THREAD

**Issue by abumphy** [Orillusion/orillusion#410]
## Describe the solution you'd like
A clear and concise description of what you want to happen

## Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered

## Additional context
Add any other context or screenshots about the feature request here

**Comment by orillusion-admin** [comment]
在整理最新版本了~最近这几个月，确实商业项目有些忙不过来~ 但是，我们后面会努力跟进的！

而且很多功能都可以沉淀到开源版本中，希望对大家能有帮助~

**Comment by Davidyanlong** [comment]
期待~
