### ISSUE TITLE
[BUG]: 统计窗口插件只显示UI，不显示FPS和内存占用的数据

### ISSUE THREAD

**Issue by cutepet** [Orillusion/orillusion#424]
## Bug描述
统计窗口插件只显示UI，不显示FPS和内存占用的数据

## 测试引擎版本:
本地运行出错的Orillusion引擎版本,  0.8.2

**Comment by lslzl3000** [comment]
能给出代码吗？或者起码截图看一下？

**Comment by lslzl3000** [comment]
这种应该是本地有多个版本 `@orillusion/core`,  `stats` 引用的和主程序引用的不是同一个版本

一般会发生于基于`vite` 和 `pnpm` 管理的项目，算是一种bug吧，比如之前是 `v0.8.1` 然后升级了 `v0.8.2`, 由于 vite缓存 和pnpm的机制，在 `node_modules` 里会出现两个版本的 `@orillusion/core` 软链接，`@orillusion/stats` 还是会引用老版本 `v0.8.1` 的引擎, 而主程序本身引用的是 `v0.8.2` 的引擎，所以 Stats 无法正常运行，实际上ts也给出了错误提示：
![Screenshot 2024-07-30 at 13 54 50](https://github.com/user-attachments/assets/9a91a05d-5422-4829-bf31-91a71c191290)

一般这种解决方法最简单的就是：
1. 删除`node_modules`，重新 `pnpm i` 一下，重新建立项目引用关系，不会重新下载所有 `dependences`， `pnpm` 会重新从全局 store 里快速建立软连接
2. 或者手动删掉 `node_modules/.vite`, 再删除 `node_modules/.pnpm/xxxx` 中的老引擎版本，再重启 dev server

**Comment by cutepet** [comment]
问题已经解决，在package-lock.json中stats会引用一个老版本 v0.7.2,删除以后就可以了
![Uploading 问题解决.png…]()

**Comment by cutepet** [comment]
![Uploading 问题解决.png…]()
