### ISSUE TITLE
[BUG]: 你这个inputSystem鼠标事件处理有点不合理

### ISSUE THREAD

**Issue by zhangwenyan** [Orillusion/orillusion#429]
看你官网的示例里面,鼠标移动到canvas外面去,鼠标事件就结束了,我就感觉怪怪的,后来我去看了threejs的示例,人家鼠标拖动到canvas外面,然后再拖动回来,鼠标拖动事件没有停止

**Comment by lslzl3000** [comment]
拖动是指？有 three.js 的例子吗

**Comment by lslzl3000** [comment]
以 three.js [oribitController](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/OrbitControls.js)为例，它没有监测 `pointerleave` event 所以，鼠标离开 canvas 不会中断状态

但确实不需要处理 leave 事件吗？ 这个很难界定哪种处理方式更好，很多情况确实鼠标离开了就是真的离开了，不需要保持状态了，不同的业务可能处理逻辑不一样

inputsystem 是底层统一处理所有事件，如果上层 controller 需要保持leave的状态，可以自行处理。目前引擎内置的 controller 都是要处理 leave 状态的，如果你的应用需要保持，可以自定义一个 controller  忽略 leave 事件即可

**Comment by lslzl3000** [comment]
尝试在 down 状态下锁定了 pointer , 可以保持交互锁定 (#432) , 下个版本会发布修复
