### ISSUE TITLE
[BUG]: 相机俯视突变

### ISSUE THREAD

**Issue by unstoppable007** [Orillusion/orillusion#430]
## Bug描述
初始时候，把相机放在原点正上方俯视原点；
初次拖动相机视角时候，视角发生突变；
是不是万向锁的处理方式问题？

## Bug复现流程
![屏幕截图 2024-07-27 115005](https://github.com/user-attachments/assets/186cf913-8f00-4410-9c5d-254999656547)

## 报错截图

https://github.com/user-attachments/assets/554195e8-d09f-453e-91a1-2fa9c6375fb4

## 测试引擎版本:
本地运行出错的Orillusion引擎版本0.8.2

**Comment by lslzl3000** [comment]
resolved #431
