### ISSUE TITLE
[FR]: 希望有个网格参考平面

### ISSUE THREAD

**Issue by unstoppable007** [Orillusion/orillusion#434]

**Comment by lslzl3000** [comment]
能给个例子参考一下吗？大概什么样子的网格平面

**Comment by unstoppable007** [comment]
![屏幕截图 2024-07-28 183442](https://github.com/user-attachments/assets/476b54ae-223e-41e2-b2a7-1d8d163f71b9)
这种 x,y平面上的网格线

**Comment by lslzl3000** [comment]
添加了一个辅助 `GridObject` 可以用来快速建立这种平面
```ts
// 大小，分割数量
let grid = new GridObject(1000, 100);
scene3D.addChild(grid)
```
会跟着 v0.8.3 发布
