### ISSUE TITLE
[BUG]: LitMaterial 设置纹理重复无效，UnLitMaterial 有效

### ISSUE THREAD

**Issue by ID-Emmett** [Orillusion/orillusion#435]
## Bug描述
![image](https://github.com/user-attachments/assets/0543187c-4bb5-45dd-ab61-3a5cde5e6025)

这是有效的：
`let mat = new UnLitMaterial(); 
mat.setUniformVector4('transformUV1', new Vector4(0, 0, 2, 2));`

这是无效的：
`let mat = new LitMaterial(); 
mat.setUniformVector4('transformUV1', new Vector4(0, 0, 2, 2));`

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, e.g. 0.8.1

**Comment by lslzl3000** [comment]
感谢反馈，下个版本会统一命名方式

**Comment by ID-Emmett** [comment]
看了下改动，0.8.3中`LitMaterial`纹理重复是这样配置的：
`mat.setUniformVector4('baseMapOffsetSize', new Vector4(0, 0, 60, 60));`
`mat.setUniformVector4('normalMapOffsetSize', new Vector4(0, 0, 60, 60));`
建议在文档说明一下
