### ISSUE TITLE
[FR]: Where are the Systems from ECS?

### ISSUE THREAD

**Issue by mreinstein** [Orillusion/orillusion#450]
Orillusion's docs say it's modeled after Entity Component Systems (ECS) but I don't see any actual systems, unless I'm missing something.

It seems like all of the logic that would normally go into a system gets baked into lifecycle functions on the components themselves (e.g., `someComponent.onUpdate`. I don't want to couple my data to my simulation logic. I want components to be pure data structures and put logic in systems that _query_ for a set of entities matching a component list.

It also seems like Orillusion is creating it's own simulation loop, but I'd rather have a way to do something like:

```javascript
import { Engine3D } from '@orillusion/core'

async function main () {
    const e = await Engine3D.init()
    while (simRunning) {
         // run my own sim logic here, run other ECS systems etc.

         e.tick()  // do Orillusion rendering
    }
}

main()
```

Is there a way to utilize orillusion for just rendering and not have to bring along all of it's ECS baggage and built in simulation loop?

**Comment by lslzl3000** [comment]
@mreinstein  good question, Orillusion basically mix the logic `system` into the `component`, it is more like a lightweight `component` based system, like [vue.js](https://vuejs.org/), rather than a strict ECS structure like some native Engines, like [bevy](https://bevyengine.org/).

We had tried a fully strict ECS version at very first beginning, but it is quite hard to learn this coding style for web/frontend developers, especially for those developers who work with OO style like `three.js` and `babylon.js`. We may try a fully strict ECS structure in the future, e.g. after 1.0 release

For the loop question,  I think you can manage a custom logic loop by call `Engine3D.updateFrame()`, it is not exposed as public method, but you can call that to do the frame rendering manually.
```ts
import { Engine3D } from '@orillusion/core'

async function main () {
    const e = await Engine3D.init()
    // .. init scene, view, and others
    
    // setup the Engine render job
    Engine3D.startRenderView(view)
    // and stop the inner loop
    Engine3D.pause()

    // use your own custom loop
    // p.s,  it is not recommend to use `while` in main thread, better with `requestAnimationFrame`
    while (simRunning) {
         // run my own sim logic here, run other ECS systems etc.
         ...
         await Engine3D.updateFrame(Performance.now())  // call Engine loop manually, run inner components lifecycle
    }
}

main()
```

Or just use the `beforeRender` hook, the main render loop will run the `beforeRender` before all inner components' lifecycle:

```ts
import { Engine3D } from '@orillusion/core'

async function logicLoop () {
    // run your own sim logic here, run other ECS systems etc.
    ...
}

async function main () {
    const e = await Engine3D.init({
        beforeRender: logicLoop  // this will be called before render loop
    })
    // start Engine render loop
    Engine3D.startRenderView(view)
}

main()
```

**Comment by mreinstein** [comment]
@lslzl3000 thanks for taking the time to respond with a thoughtful post!  I'm not trying to pick on Orillusion, I'm just trying to evaluate if it's right for my next project, and if there's some way to use a more pure ECS approach. I really don't like scene graphs and coupling data to code, so these questions are all about that stuff. I love how polished this engine is, and the docs are great.


> We had tried a fully strict ECS version at very first beginning, but it is quite hard to learn this coding style for web/frontend developers

Essentially it is a database, and you can query it.  That's a tech that web developers are very comfortable with.  Maybe you just need a good visualization or explanation of how ECS works.  Something that is far more foreign to web developers are matrix math and perspective transforms, but Orillusion hasn't avoided that. :)

> you can manage a custom logic loop by call Engine3D.updateFrame()

Thanks! A question on that; why does it take in `performance.now()` as an argument?  My understanding is that function returns high resolution time since the initial page load.  I'm concerned about what happens if the window is minimized for a while, and a user re-activates the page.  that's going to be a big jump in clock time. So for example:

```
await Engine3D.updateFrame(961701)  
await Engine3D.updateFrame(961777)  // 16ms
await Engine3D.updateFrame(961793)  // 16ms

// *BROWSER TAB SUSPENDED*

// some time passes

// *BROWSER TAB RESUMED*

await Engine3D.updateFrame(1404555) // whoa, big jump since last updateFrame call
```

**Comment by lslzl3000** [comment]
the `updateFrame` should be a callback for `requestAnimationFrame`, so the argument  is a `timestamp`, which should be equal to [document.timeline.currentTime](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame), it is also similar to calling `performance.now()` at most cases.

>     // p.s,  it is not recommend to use `while` in main thread, better with `requestAnimationFrame`

so, a good loop should be
```ts
function loop(){
    requestAnimationFrame(async (timestamp)=>{
        // ...
        await Engine3D.updateFrame(timestamp)
        loop() // call loop to start next frame
    })
}
```

As for the `big jump` of `timestamp`, as an engine, we just save the time, and mainly use the `Time.frame` value. How to use the `Time.delta` or `Time.time` depends on user logic.
```ts
async updateFrame(time:number){
  Time.delta = time - Time.time;
  Time.time = time;
  Time.frame += 1;
  ...
}
```
Some of the internal components depend on the `Time.delta`, e.g. camera controllers, but it is during user interaction(certainly the active page), which should not have a big jump value. In your custom loop, you should take care of the `delta`, but it won't take too much effects for engine rendering
