### ISSUE TITLE
[FR]: Get Global Coordinate

### ISSUE THREAD

**Issue by liukunace** [Orillusion/orillusion#454]
## Is your feature request related to a problem? Please describe

有个技术问题需要帮确认下下，我需要得到鼠标点击点的全局坐标值，画布上某点的全局相对坐标是不变的，为了在上面处理地理空间数据，比如说地理点的坐标不会因为相机视角变化而变化，目前有MouthX/Y属于屏幕坐标，会根据场景移动变化，引擎api里没找到获取全局坐标的函数，不知道有没有实现。

![微信图片_20241127143551](https://github.com/user-attachments/assets/c7b8b31b-278c-4839-878d-541ff14c4c9d)

**Comment by lslzl3000** [comment]
0.8.3 和以前的版本中 bound 模式下缺失添加 pick 结果，该问题已在dev分支上修复，稍后会发布 0.8.4
