### ISSUE TITLE
[BUG]: TAAPost开启后整体场景轻微抖动且模型不断向屏幕右边偏移

### ISSUE THREAD

**Issue by ZhengWeiming233** [Orillusion/orillusion#458]
## Bug描述
TAAPost开启后整体场景轻微抖动且不断向屏幕右边偏移

## Bug复现流程
通过以下步骤产生bug:
1. 创建场景，场景中添加一个模型。
2. 添加TAAPost。
3. 整体场景轻微抖动，且模型不断向右偏移（也有可能是相机向左偏移）。

## 期待的结果
场景不抖动，模型（或相机）不偏移。

## 报错截图

https://github.com/user-attachments/assets/ad407db1-c218-4e80-9652-80bc8026c254

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, "@orillusion/core": "^0.8.4"

## 本机系统 (请填写完整):
 - OS: [windows10]
 - Browser: [e.g]
 - Version: [e.g. 版本 131.0.2903.112 (正式版本) (64 位)]

## 本机配置
- CPU: CPU Hygon C86 3350 8-coreProcessor 
- Graphics Card: GTX 4000

## 代码示例
![image](https://github.com/user-attachments/assets/f80761e4-3b92-4cc9-aac0-d604a966af6e)

**Comment by ZhengWeiming233** [comment]
显卡是RTX4000，在RTX3060电脑上也测试过代码，有时候抖动，有时候不抖动

**Comment by lslzl3000** [comment]
感谢反馈，TAA 效果通常是引入抖动（jittering）技术，将相机的位置持续进行轻微抖动来完成对采样点的随机偏移，它更适合处理动态复杂场景，对于静态下的画面，微小抖动才会比较明显，尤其是例如上面的这种小尺寸场景，相机的偏移看起来会更明显一些。

引擎中可以根据场景大小来调整  `temporalJitterScale` 来手动降低抖动的偏移量，降低相机位移的副作用
```ts
type TAASetting = {
    enable: boolean;
    /**
     * The number of random seed for dithering camera is 8 by default.
     * Reducing the number can solve some problems with noticeable jitter, but the jagginess will become more pronounced
     */
    jitterSeedCount: number;
    /**
     * Merge the coefficients of the historical frame and the current frame. The smaller the parameter, the smaller the proportion of the current frame
     */
    blendFactor: number;
    /**
     * The scaling coefficient of the random offset value of the jitter camera [0,1]: The smaller the coefficient, the weaker the anti aliasing effect, and the weaker the pixel jitter
     */
    temporalJitterScale: number;
    /**
     * Image sharpening coefficient [0.1-0.9]: The smaller the coefficient, the weaker the sharpening effect, the better the anti aliasing effect. Conversely, the stronger the sharpening, the weaker the anti aliasing effect
     */
    sharpFactor: number;
    /**
     * Image sharpening sampling coefficient scaling coefficient: Scales the sampling offset during sharpening.
     */
    sharpPreBlurFactor: number;
};

```

我们稍后也会尝试一些优化策略，比如相机静止状态下主动降低 `temporalJitterScale` 甚至调到 `0` 来降低静态画面的抖动情况

至于相机会持续向左/右偏移，我们也排查一下，稍后优化一下

**Comment by lslzl3000** [comment]
> 相机会持续向左/右偏移，我们也排查一下，稍后优化一下

可以尝试 `@orillusion/core@0.8.5-dev.3`，应该修复了持续偏移问题，抖动问题目前还是按场景大小设置合适的 `temporalJitterScale` 为主

**Comment by ZhengWeiming233** [comment]
> > 相机会持续向左/右偏移，我们也排查一下，稍后优化一下
> 
> 可以尝试 `@orillusion/core@0.8.5-dev.3`，应该修复了持续偏移问题，抖动问题目前还是按场景大小设置合适的 `temporalJitterScale` 为主

好的，感谢解答，更新此版本后基本看不出来抖动，偏移问题已解决。

**Comment by ZhengWeiming233** [comment]
更新版本后已解决。

**Comment by ZhengWeiming233** [comment]
更新版本后已解决。
