### ISSUE TITLE
Cannot resolve dependency

### ISSUE THREAD

**Issue by baimingl** [Orillusion/orillusion#5]
![image](https://user-images.githubusercontent.com/47734049/225535842-c827c8b8-e759-4607-abd8-2b9a2675d066.png)

**Comment by lslzl3000** [comment]
Vite or  WebPack?
The `dat.gui.module.js` is a native `es module` import from url, which should be in pure native JS module or Vite

We don't use WebPack, the default config of Webpack may not work load ES module from url, you can check the webpack doc to find a solution

**Comment by ImpChiang** [comment]
![image](https://user-images.githubusercontent.com/31588565/232990132-71a3da0e-af32-4085-bf51-361adf574792.png)
similiar in use vite

**Comment by lslzl3000** [comment]
Removed in 0.6+
