### ISSUE TITLE
部分glb文件无法显示

### ISSUE THREAD

**Issue by pwlviolet** [Orillusion/orillusion#7]
使用 [Engine3D.res.loadGltf](https://www.orillusion.com/api/classes/Res.html#loadgltf) 来加载 glb 模型，无法加载某些glb文件，问题如下图
![image](https://user-images.githubusercontent.com/74035710/225915002-da66e2d0-5abe-4d61-8687-241a7124cebc.png)
无法加载的模型文件为https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf   下的Horse.glb
部分模型可以加载
![image](https://user-images.githubusercontent.com/74035710/225917995-9fa1cd58-094c-40f5-8f70-1ab8899b05f7.png)
![2](https://user-images.githubusercontent.com/74035710/225918058-b220c0e4-541c-4b39-8e03-ea33b1835141.png)
可以加载的模型为https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf  下的Flower.glb和BoomBox.glb，暂时只尝试了这三个模型，希望能够优化或者在文档中提示一下。

Chrome
 
版本 113.0.5657.0（正式版本）canary （64 位）

Vite +Vue3

**Comment by Codeboy-cn** [comment]
`Horse.glb` 中包含一个 morph实现的马匹奔跑动画，该文件在  `Engine 0.5.0` 中能正常加载，但morph动画的播放似乎有点问题，该 `#7 issues` 涉及的问题正在排期，我们将尽快修复。

**Comment by sunvangh** [comment]
加载 BoomBox.glb 模型，刚开始看不到，后来发现 放大几倍就 好了
